const cityObjs = {
  cities: [
    { id: 0, name: "Albuquerque", state: "NM" },
    { id: 0, name: "Atlanta", state: "GA" },
    { id: 0, name: "Austin", state: "TX" },
    { id: 0, name: "Baltimore", state: "MA" },
    { id: 0, name: "Boston", state: "MA" },
    { id: 0, name: "Charlotte", state: "NC" },
    { id: 0, name: "Chicago", state: "IL" },
    { id: 0, name: "Colorado Springs", state: "CO" },
    { id: 0, name: "Columbus", state: "OH" },
    { id: 0, name: "Dallas", state: "TX" },
    { id: 0, name: "Denver", state: "CO" },
    { id: 0, name: "Detroit", state: "MI" },
    { id: 0, name: "Honolulu", state: "HI" },
    { id: 0, name: "Houston", state: "TX" },
    { id: 0, name: "Indianapolis", state: "IN" },
    { id: 0, name: "Jacksonville", state: "FL" },
    { id: 0, name: "Kansas City", state: "KS" },
    { id: 0, name: "Las Vegas", state: "NV" },
    { id: 0, name: "Los Angeles", state: "CA" },
    { id: 0, name: "Louisville", state: "KY" },
    { id: 0, name: "Memphis", state: "TN" },
    { id: 0, name: "Miami", state: "FL" },
    { id: 0, name: "Milwaukee", state: "WI" },
    { id: 0, name: "Minneapolis", state: "MN" },
    { id: 0, name: "Nashville", state: "TN" },
    { id: 0, name: "New York", state: "NY" },
    { id: 0, name: "Oakland", state: "CA" },
    { id: 0, name: "Oklahoma City", state: "OK" },
    { id: 0, name: "Philidelphia", state: "PA" },
    { id: 0, name: "Phoenix", state: "AZ" },
    { id: 0, name: "Portland", state: "OR" },
    { id: 0, name: "Raleigh", state: "NC" },
    { id: 0, name: "San Antonio", state: "CA" },
    { id: 0, name: "San Diego", state: "CA" },
    { id: 0, name: "San Francisco", state: "CA" },
    { id: 0, name: "San Jose", state: "CA" },
    { id: 0, name: "Seattle", state: "WA" },
  ],
};

const newCitiesObj = cityObjs.cities.map((city, idx) => {
  return { id: idx + 1, name: city.name, state: city.state };
});

const cityNameSlugs = {
  cities: [
    "Albuquerque,%20NM",
    "Atlanta,%20GA",
    "Austin,%20TX",
    "Baltimore,%20MD",
    "Boston,%20MA",
    "Charlotte,%20NC",
    "Chicago,%20IL",
    "Colorado%20Springs,%20CO",
    "Columbus,%20OH",
    "Dallas,%20TX",
    "Denver,%20CO",
    "Detroit,%20MI",
    "Honolulu,%20HI",
    "Houston,%20TX",
    "Indianapolis,%20IN",
    "Jacksonville,%20FL",
    "Kansas%20City,%20KS",
    "Las%20Vegas,%20NV",
    "Los%20Angeles,%20CA",
    "Louisville,%20KY",
    "Memphis,%20TN",
    "Miami,%20FL",
    "Milwaukee,%20WI",
    "Minneapolis,%20MN",
    "Nashville,%20TN",
    "New%20York,%20NY",
    "Oakland,%20CA",
    "Oklahoma%20city,%20OK",
    "Philadelphia,%20PA",
    "Phoenix,%20AZ",
    "Portland,%20OR",
    "Raleigh,%20NC",
    "San%20Antonio,%20TX",
    "San%20Diego,%20CA",
    "San%20Francisco,%20CA",
    "San%20Jose,%20CA",
    "Seattle,%20WA",
  ],
};

const cityNameFormats = {
  newCitiesObj,
  cityNameSlugs,
};

module.exports = cityNameFormats;
