const cityObjs = {
  cities: [
    { id: 0, name: "Albuquerque", state: "NM", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/albuquerque-f730c0301f.jpg", imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/albuquerque_web-3079b54e59.jpg"},
    { id: 0, name: "Atlanta", state: "GA", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/atlanta-9e33744cb4.jpg", imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/atlanta_web-01e0d78232.jpg"},
    { id: 0, name: "Austin", state: "TX", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/austin-f42354c37f.jpg" , imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/austin_web-e93a5e75a0.jpg"},
    { id: 0, name: "Baltimore", state: "MA", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/baltimore-14c1f65307.jpg", imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/baltimore_web-251806a8b8.jpg"},
    { id: 0, name: "Boston", state: "MA", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/boston-7399414b98.jpg", imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/boston_web-550bb970ba.jpg"},
    { id: 0, name: "Charlotte", state: "NC", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/charlotte-acc065366a.jpg", imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/charlotte_web-062d6f0cd8.jpg"},
    { id: 0, name: "Chicago", state: "IL" , imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/chicago-1e610b84c3.jpg", imageUrlWeb:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/chicago_web-b20b0b8249.jpg"},
    { id: 0, name: "Colorado Springs", state: "CO", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/colorado-springs-ccf32e73d2.jpg" , imageUrlWeb:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/colorado-springs_web-a8228d2190.jpg"},
    { id: 0, name: "Columbus", state: "OH", imageUrlMobile:"https://api.teleport.org/api/urban_areas/slug:columbus/", imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/columbus_web-748d46d705.jpg"},
    { id: 0, name: "Dallas", state: "TX", imageUrlMobile:"https://api.teleport.org/api/urban_areas/slug:dallas/" , imageUrlWeb:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/dallas_web-1b0ab83512.jpg"},
    { id: 0, name: "Denver", state: "CO", imageUrlMobile:"https://api.teleport.org/api/urban_areas/slug:denver/" , imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/denver_web-9726d88300.jpg"},
    { id: 0, name: "Detroit", state: "MI", imageUrlMobile:"https://api.teleport.org/api/urban_areas/slug:detroit/", imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/detroit_web-fa9062b00a.jpg"},
    { id: 0, name: "Honolulu", state: "HI", imageUrlMobile:"https://api.teleport.org/api/urban_areas/slug:honolulu/", imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/honolulu_web-1b1279edc3.jpg"},
    { id: 0, name: "Houston", state: "TX", imageUrlMobile: "https://api.teleport.org/api/urban_areas/slug:houston/", imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/houston_web-7a1ff7109f.jpg"},
    { id: 0, name: "Indianapolis", state: "IN", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/indianapolis-0f293b1150.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/indianapolis_web-de0ee7a5bd.jpg"},
    { id: 0, name: "Jacksonville", state: "FL", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/jacksonville-62a5b94ba8.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/jacksonville_web-cc69395f3f.jpg"},
    { id: 0, name: "Kansas City", state: "KS", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/kansas-city-1e8f1c1456.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/kansas-city_web-d977356d14.jpg"},
    { id: 0, name: "Las Vegas", state: "NV", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/las-vegas-6acb21a1fe.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/las-vegas_web-7dc177ab7c.jpg"},
    { id: 0, name: "Los Angeles", state: "CA", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/los-angeles-f5b60deb04.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/los-angeles_web-2eedb2a83e.jpg"},
    { id: 0, name: "Louisville", state: "KY", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/louisville-d5997729f5.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/louisville_web-af543d6a99.jpg"},
    { id: 0, name: "Memphis", state: "TN", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/memphis-6135da61bc.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/memphis_web-6015ce820e.jpg"},
    { id: 0, name: "Miami", state: "FL" , imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/miami-730928937f.jpg",
    imageUrlWeb:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/miami_web-9307474a5e.jpg"},
    { id: 0, name: "Milwaukee", state: "WI", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/milwaukee-aa45ba9b6b.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/milwaukee_web-59a01d05ad.jpg"},
    { id: 0, name: "Minneapolis", state: "MN", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/minneapolis-saint-paul-0167dd447d.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/minneapolis-saint-paul_web-16dbfd4210.jpg"},
    { id: 0, name: "Nashville", state: "TN", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/nashville-79d8242c30.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/nashville_web-928afede11.jpg"},
    { id: 0, name: "New York", state: "NY", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/new-york-9cb6cc2ae5.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/new-york_web-99d9bb0809.jpg"},
    { id: 0, name: "Oakland", state: "CA"},
    { id: 0, name: "Oklahoma City", state: "OK", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/oklahoma-city-429f6bf45d.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/oklahoma-city_web-2d2437c3f2.jpg"},
    { id: 0, name: "Philadelphia", state: "PA", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/philadelphia-41bf6ab8ef.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/philadelphia_web-ebd7cad1dc.jpg"},
    { id: 0, name: "Phoenix", state: "AZ", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/phoenix-9fedc88f57.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/phoenix_web-92224752db.jpg"},
    { id: 0, name: "Portland", state: "OR", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/portland-or-90f71ea149.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/portland-or_web-55a07378b0.jpg"},
    { id: 0, name: "Raleigh", state: "NC", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/raleigh-e74249142f.jpg",
    imageUrlWeb:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/raleigh_web-2909c09abe.jpg"},
    { id: 0, name: "San Antonio", state: "CA", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/san-antonio-462487f470.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/san-antonio_web-37402dd546.jpg"},
    { id: 0, name: "San Diego", state: "CA", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/san-diego-50187120db.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/san-diego_web-2be4eba8b4.jpg", },
    { id: 0, name: "San Francisco", state: "CA", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/san-francisco-bay-area-7f6d130d20.jpg",
    imageUrlWeb:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/san-francisco-bay-area_web-f17b1f60e6.jpg"},
    { id: 0, name: "San Jose", state: "CA", imageUrlMobile: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/san-jose-0a8dfb4120.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/san-jose_web-c73054cc3d.jpg"},
    { id: 0, name: "Seattle", state: "WA", imageUrlMobile:"https://d13k13wj6adfdf.cloudfront.net/urban_areas/seattle-9bc4830d22.jpg",
    imageUrlWeb: "https://d13k13wj6adfdf.cloudfront.net/urban_areas/seattle_web-e07e580eca.jpg"},
  ],
};

const newCitiesObj = cityObjs.cities.map((city, idx) => {
  return { id: idx + 1, name: city.name, state: city.state };
});

const cityNameSlugs = {
  cities: [
    "Albuquerque,%20NM",
    "Atlanta,%20GA",
    "Austin,%20TX",
    "Baltimore,%20MD",
    "Boston,%20MA",
    "Charlotte,%20NC",
    "Chicago,%20IL",
    "Colorado%20Springs,%20CO",
    "Columbus,%20OH",
    "Dallas,%20TX",
    "Denver,%20CO",
    "Detroit,%20MI",
    "Honolulu,%20HI",
    "Houston,%20TX",
    "Indianapolis,%20IN",
    "Jacksonville,%20FL",
    "Kansas%20City,%20KS",
    "Las%20Vegas,%20NV",
    "Los%20Angeles,%20CA",
    "Louisville,%20KY",
    "Memphis,%20TN",
    "Miami,%20FL",
    "Milwaukee,%20WI",
    "Minneapolis,%20MN",
    "Nashville,%20TN",
    "New%20York,%20NY",
    "Oakland,%20CA",
    "Oklahoma%20city,%20OK",
    "Philadelphia,%20PA",
    "Phoenix,%20AZ",
    "Portland,%20OR",
    "Raleigh,%20NC",
    "San%20Antonio,%20TX",
    "San%20Diego,%20CA",
    "San%20Francisco,%20CA",
    "San%20Jose,%20CA",
    "Seattle,%20WA",
  ],
};

const cityNameFormats = {
  newCitiesObj,
  cityNameSlugs,
};

module.exports = cityNameFormats;
